version: '3.8'

services:
  django:
    container_name: onlinecourse
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/onlinecourse
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=course_admin
      - POSTGRES_PASSWORD=adminpassword2023
      - POSTGRES_DB=course_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: