version: '3.8'

services:
  django:
    container_name: onlinecourse
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: ${POSTGRES_DB}
    volumes:
      - .env.example:/onlinecourse/.env
      - .:/onlinecourse
    depends_on:
      - db
    links:
      - db
    # networks:
    #   - courseNetwork
  db:
    image: postgres:latest
    restart: always
    hostname: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # networks:
    #   - courseNetwork
volumes:
  postgres_data:

# networks:
#   courseNetwork:
