# Generated by Django 4.2.3 on 2023-07-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hls_manifest',
            field=models.FileField(blank=True, null=True, upload_to='hls/'),
        ),
    ]
