# Generated by Django 4.2.3 on 2023-07-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_video_hls_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='preview/'),
        ),
    ]
