# Generated by Django 4.2.3 on 2023-07-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dash_manifest',
            field=models.FileField(blank=True, null=True, upload_to='dash/'),
        ),
    ]
