# Generated by Django 4.2.3 on 2023-07-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_profile_instructor_alter_course_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name_plural': 'SystemSettings'},
        ),
    ]
