# Generated by Django 4.2.3 on 2023-07-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_notification_alter_message_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_image',
            field=models.ImageField(null=True, upload_to='courses/'),
        ),
    ]
