# Generated by Django 4.2.3 on 2023-07-26 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='section',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='section',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.CreateModel(
            name='VideoDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.document')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.section')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.video')),
            ],
        ),
    ]
