# Generated by Django 4.2.3 on 2023-07-26 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_document_section_remove_document_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='videodocument',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
