# Generated by Django 4.2.3 on 2023-08-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_answer_instructor_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodocument',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='courses.section'),
        ),
    ]
