# Generated by Django 4.2.3 on 2023-08-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_videodocument_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('one_time', 'One time'), ('monthly', 'Monthly')], default='mpesa', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('one_time', 'One time'), ('monthly', 'Monthly')], default='monthly', max_length=100, null=True),
        ),
    ]
