# Generated by Django 4.2.3 on 2023-08-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_subscription_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'Mpesa'), ('paypal', 'Paypal')], default='mpesa', max_length=100, null=True),
        ),
    ]
