# Generated by Django 4.2.3 on 2023-08-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_subscription_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='one_time_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
