# Generated by Django 4.2.3 on 2023-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_course_monthly_price_course_one_time_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='monthly_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='one_time_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
