# Generated by Django 4.2.3 on 2023-08-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_course_options_course_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
