# Generated by Django 4.2.3 on 2023-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_video_processing_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodocument',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
